### ISSUE TITLE
Can't get song_titles to work... 

### ISSUE THREAD

**Issue by brennanpincardiff** [CaRdiffR/tidy_thursdays#2]
Just to warn you, I can't get the song_titles.R script to work. 
Some issue with the group_by... 
We can talk about it more tonight. 
I tried change the week_id into dates using mdy() but that created a different error. 
I'll try again if I have time before tonight. 
Cheers, Paul

**Comment by dokato** [comment]
Thanks @brennanpincardiff for spotting that. I forgot to transform `week_id` to Date type, so lubridate function `floor_date` wasn't happy about that.

This is fixed now with https://github.com/CaRdiffR/tidy_thursdays/commit/e631a076233e08abb57ab3d690a12f5fff700f18
